// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Last_Dance_Project.Data;

#nullable disable

namespace The_Last_Dance_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327234514_UpdateNewRole")]
    partial class UpdateNewRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("The_Last_Dance_Project.Models.AuditEntity", b =>
                {
                    b.Property<long>("MtTranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MTTRANID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MtTranId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ACTIONDATE");

                    b.Property<DateTime>("BusDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BUSDATE");

                    b.Property<string>("Checker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHECKER");

                    b.Property<string>("ChkIpAddress")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CHKIPADDRESS");

                    b.Property<string>("ChkWsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHKWSNAME");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("KeyField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KEYFIELD");

                    b.Property<string>("KeyFieldExt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KEYFIELDEXT");

                    b.Property<string>("KeyValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("KEYVALUE");

                    b.Property<string>("KeyValueExt")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("KEYVALUEEXT");

                    b.Property<string>("MaIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAIPADDRESS");

                    b.Property<string>("MaWsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAWSNAME");

                    b.Property<string>("Maker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAKER");

                    b.Property<string>("ModCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MODCODE");

                    b.Property<string>("MtlStatus")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("MTLSTATUS");

                    b.Property<string>("MtlType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("MTLTYPE");

                    b.Property<string>("ObjChange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OBJCHANGE");

                    b.HasKey("MtTranId");

                    b.ToTable("MTTRAN", (string)null);

                    b.HasData(
                        new
                        {
                            MtTranId = 1001L,
                            ActionDate = new DateTime(2026, 3, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            BusDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tạo tài khoản maker_system",
                            KeyField = "CustId",
                            KeyValue = "ACC_MAKER_001",
                            Maker = "maker_system",
                            ModCode = "CUST",
                            MtlStatus = "A",
                            MtlType = "A",
                            ObjChange = "Customer"
                        },
                        new
                        {
                            MtTranId = 1002L,
                            ActionDate = new DateTime(2026, 3, 27, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            BusDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tạo tài khoản",
                            KeyField = "AccId",
                            KeyValue = "ACC_0001",
                            Maker = "maker_system",
                            ModCode = "ACC",
                            MtlStatus = "A",
                            MtlType = "C",
                            ObjChange = "Account"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.AuditEntityKey", b =>
                {
                    b.Property<long>("MtTranFldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MTTRANFLDID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MtTranFldId"));

                    b.Property<long?>("AuditentityMtTranId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColumnName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COLUMNNAME");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("DisplayNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYNAMEEN");

                    b.Property<string>("DisplayValNew")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("DISPLAYVALNEW");

                    b.Property<string>("DisplayValOld")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("DISPLAYVALOLD");

                    b.Property<string>("KeyMap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("KEYMAP");

                    b.Property<string>("KeyMapEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("KEYMAPEN");

                    b.Property<long>("MtTranId")
                        .HasColumnType("bigint")
                        .HasColumnName("MTTRANID");

                    b.Property<string>("NewVal")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("NEWVAL");

                    b.Property<string>("NewValEn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("NEWVALEN");

                    b.Property<string>("OldVal")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("OLDVAL");

                    b.Property<string>("OldValEn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("OLDVALEN");

                    b.Property<string>("TabName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TABNAME");

                    b.Property<string>("TabNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TABNAMEEN");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TABLENAME");

                    b.HasKey("MtTranFldId");

                    b.HasIndex("AuditentityMtTranId");

                    b.HasIndex("MtTranId");

                    b.ToTable("AUDITENTITY_KEY", (string)null);

                    b.HasData(
                        new
                        {
                            MtTranFldId = 2001L,
                            ColumnName = "NAME",
                            DisplayName = "Tên",
                            MtTranId = 1001L,
                            NewVal = "Maker System Account",
                            TabName = "Thông tin khách hàng",
                            TableName = "CUSTOMER"
                        },
                        new
                        {
                            MtTranFldId = 2002L,
                            ColumnName = "EMAIL",
                            DisplayName = "Email",
                            MtTranId = 1001L,
                            NewVal = "maker_sys@test.com",
                            TabName = "Thông tin khách hàng",
                            TableName = "CUSTOMER"
                        },
                        new
                        {
                            MtTranFldId = 2003L,
                            ColumnName = "STATUS",
                            DisplayName = "Trạng thái",
                            MtTranId = 1002L,
                            NewVal = "Active",
                            TabName = "Thông tin tài khoản",
                            TableName = "ACCOUNT"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.AuditEntityKeyDefinition", b =>
                {
                    b.Property<int>("DefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEFID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COLUMNNAME");

                    b.Property<string>("DataType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DATATYPE");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("DisplayNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYNAMEEN");

                    b.Property<string>("IsCompare")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ISCOMPARE");

                    b.Property<string>("LookupTable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LOOKUPTABLE");

                    b.Property<string>("TabName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TABNAME");

                    b.Property<string>("TabNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TABNAMEEN");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TABLENAME");

                    b.HasKey("DefId");

                    b.ToTable("AUDITENTITY_KEY_DEFINITION", (string)null);

                    b.HasData(
                        new
                        {
                            DefId = 1,
                            ColumnName = "NAME",
                            DataType = "VARCHAR2",
                            DisplayName = "Tên",
                            IsCompare = "Y",
                            TableName = "CUSTOMER"
                        },
                        new
                        {
                            DefId = 2,
                            ColumnName = "EMAIL",
                            DataType = "VARCHAR2",
                            DisplayName = "Email",
                            IsCompare = "Y",
                            TableName = "CUSTOMER"
                        },
                        new
                        {
                            DefId = 3,
                            ColumnName = "STATUS",
                            DataType = "VARCHAR2",
                            DisplayName = "Trạng thái",
                            IsCompare = "Y",
                            TableName = "ACCOUNT"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.Customer", b =>
                {
                    b.Property<string>("CustId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ApproveBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CloseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustodyCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATCA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsStaff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastChangeBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RegistrationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectDes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentCountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleId1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignPaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustId = "ACC_MAKER_001",
                            CreatedDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maker_sys@test.com",
                            Name = "Maker System Account",
                            PasswordHash = "$2a$11$qR7i5J2k5W.O7pL7X/f8/.hHqXmZ.xH1v5B8j0C9iE8A1D1G1I1K1",
                            RecordStatus = "1",
                            RoleId = "MAKER",
                            Status = "Active",
                            UserName = "maker_system"
                        },
                        new
                        {
                            CustId = "ACC_CHECKER_001",
                            CreatedDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "checker_sys@test.com",
                            Name = "Checker System Account",
                            PasswordHash = "$2a$11$qR7i5J2k5W.O7pL7X/f8/.hHqXmZ.xH1v5B8j0C9iE8A1D1G1I1K1",
                            RecordStatus = "1",
                            RoleId = "CHECKER",
                            Status = "Active",
                            UserName = "checker_system"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.CustomerContact", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FaxAttention")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InfoType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IsDefault")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ContactId");

                    b.HasIndex("CustId");

                    b.ToTable("CUSTOMER_CONTACT");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "MAKER",
                            Description = "Create and modify requests",
                            Name = "Maker"
                        },
                        new
                        {
                            RoleId = "USER",
                            Description = "User account",
                            Name = "User"
                        },
                        new
                        {
                            RoleId = "CHECKER",
                            Description = "Approve or reject requests",
                            Name = "Checker"
                        },
                        new
                        {
                            RoleId = "ADMIN",
                            Description = "Approve or reject requests and Manage System",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.SystemCode", b =>
                {
                    b.Property<string>("SystemCodeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SYSTEMCODEID");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("SystemCodeId");

                    b.ToTable("SYSTEMCODE", (string)null);

                    b.HasData(
                        new
                        {
                            SystemCodeId = "ROLE",
                            Description = "Application roles",
                            IsActive = "Y",
                            Name = "Role definitions"
                        },
                        new
                        {
                            SystemCodeId = "STATUS",
                            Description = "Statuses for MTTRAN",
                            IsActive = "Y",
                            Name = "Transaction Status"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.SystemCodeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODEVALUE");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYVALUE");

                    b.Property<string>("DisplayValueEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DISPLAYVALUEEN");

                    b.Property<string>("IsDefault")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ISDEFAULT");

                    b.Property<int?>("OrderBy")
                        .HasColumnType("int")
                        .HasColumnName("ORDERBY");

                    b.Property<string>("SystemCodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SYSTEMCODEID");

                    b.HasKey("Id");

                    b.HasIndex("SystemCodeId");

                    b.ToTable("SYSTEMCODE_VALUE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CodeValue = "ADMIN",
                            DisplayValue = "Administrator",
                            DisplayValueEn = "Administrator",
                            IsDefault = "N",
                            OrderBy = 1,
                            SystemCodeId = "ROLE"
                        },
                        new
                        {
                            Id = 1002,
                            CodeValue = "USER",
                            DisplayValue = "User",
                            DisplayValueEn = "User",
                            IsDefault = "Y",
                            OrderBy = 2,
                            SystemCodeId = "ROLE"
                        },
                        new
                        {
                            Id = 1003,
                            CodeValue = "MANAGER",
                            DisplayValue = "Manager",
                            DisplayValueEn = "Manager",
                            IsDefault = "N",
                            OrderBy = 3,
                            SystemCodeId = "ROLE"
                        },
                        new
                        {
                            Id = 1004,
                            CodeValue = "MAKER",
                            DisplayValue = "Maker",
                            DisplayValueEn = "Maker",
                            IsDefault = "N",
                            OrderBy = 4,
                            SystemCodeId = "ROLE"
                        },
                        new
                        {
                            Id = 1005,
                            CodeValue = "CHECKER",
                            DisplayValue = "Checker",
                            DisplayValueEn = "Checker",
                            IsDefault = "N",
                            OrderBy = 5,
                            SystemCodeId = "ROLE"
                        });
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.TokenBlacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TokenBlacklists");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.AuditEntityKey", b =>
                {
                    b.HasOne("The_Last_Dance_Project.Models.AuditEntity", "Auditentity")
                        .WithMany()
                        .HasForeignKey("AuditentityMtTranId");

                    b.HasOne("The_Last_Dance_Project.Models.AuditEntity", null)
                        .WithMany("Keys")
                        .HasForeignKey("MtTranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditentity");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.Customer", b =>
                {
                    b.HasOne("The_Last_Dance_Project.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("The_Last_Dance_Project.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.CustomerContact", b =>
                {
                    b.HasOne("The_Last_Dance_Project.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.SystemCodeValue", b =>
                {
                    b.HasOne("The_Last_Dance_Project.Models.SystemCode", "SystemCode")
                        .WithMany("Values")
                        .HasForeignKey("SystemCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemCode");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.AuditEntity", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("The_Last_Dance_Project.Models.SystemCode", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
